services:
  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.12
    init: true
    volumes:
      - ./:/home/python/lead-update
    working_dir: /home/python/lead-update

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/informatica-na-presales-ops/lead-update
    init: true
    volumes:
      - ./:/home/python/lead-update
    working_dir: /home/python/lead-update
