services:
  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/informatica-na-presales-ops/lead-update
    init: true
    volumes:
      - ./:/home/python/lead-update
    working_dir: /home/python/lead-update
